# Generated by Django 3.1.4 on 2020-12-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=140)),
                ('estado', models.BooleanField()),
            ],
            options={
                'ordering': ['texto'],
            },
        ),
    ]
